### ISSUE TITLE
source-map-support needs to be be updated to fix issues with native js

### ISSUE THREAD

**Issue by jonyeezs** [tschaub/karma-source-map-support#8]
I've been having issues with using native js. ie Array.map.

When i have a spec that fails in the map, source-map-support seems to try to retrieve that js file, which doesn't exist because it's native to the js engine.

This is a known issue: https://github.com/evanw/node-source-map-support/pull/130
and a fix for it is available in version 0.4.1.

Could we re-version karma-source-map-support to
`"source-map-support": "^0.4.1"`

**Comment by jonyeezs** [comment]
Hi @tschaub, will this have a release soon?

**Comment by tschaub** [comment]
Fix published as `karma-source-map-support@1.2.0`.  Thanks @jonyeezs.
